name: Weather Data Analysis

on:
  push:
    paths:
      - 'Data/csv/combined.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib

    - name: Run analysis script
      run: python scripts/analyse_weather.py

    - name: Upload analysis results to GitHub Pages
      run: |
        mkdir -p docs
        cp Data/analysed_data/*.png docs/
        echo "<html><body>" > docs/index.html
        for img in docs/*.png; do
          echo "<img src=\"$img\" style=\"width:100%;\"><br>" >> docs/index.html
        done
        echo "</body></html>" >> docs/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
